[test]
root = "src/__tests__"
timeout = 10000
isolate = true
coverage = false
coverageDir = "coverage"
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = [
  "src/__tests__/",
  "src/index.ts",
  "src/types/",
  "dist/",
  "node_modules/",
]
